# -*- coding: utf-8 -*-
"""Hope-Nyambura_cs-eh03-25100-MLOPs-BONUS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ycBBW1xzH1ltRTuikhs13BBR4lXOOrL
"""

# Hope Njoki Nyambura
# Student ID: cs-eh03-25100
# Cyber Shujaa Program - Week 9 Bonus
# Streamlit App Integration (MLOPs)

# Install required libraries
!pip install streamlit scikit-learn pandas numpy

# Import necessary libraries
import streamlit as st
import pandas as pd
import numpy as np
import pickle
from pathlib import Path

# List files in sample_data just to check
!ls /content/sample_data

# Load the training data
train_data_path = '/content/sample_data/california_housing_train.csv'
train_df = pd.read_csv(train_data_path)

# Inspect the first few rows of the training data
train_df.head()

# Prepare features and target
X = train_df.drop('median_house_value', axis=1)
y = train_df['median_house_value']

# Check shapes
X.shape, y.shape

# Split data into features (X) and target (y)
X = train_df.drop('median_house_value', axis=1)
y = train_df['median_house_value']

# Split into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Check the shapes
X_train.shape, X_test.shape, y_train.shape, y_test.shape

# Import model
from sklearn.ensemble import RandomForestRegressor

# Create the model
model = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model
model.fit(X_train, y_train)

# Check training score
model.score(X_train, y_train)

# Check model score on test data
test_score = model.score(X_test, y_test)
test_score

# Save the trained model
model_path = '/content/sample_data/random_forest_model.pkl'
with open(model_path, 'wb') as f:
    pickle.dump(model, f)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile streamlit_app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import pickle
# 
# train_data_path = "/content/sample_data/california_housing_train.csv"
# train_df = pd.read_csv(train_data_path)
# 
# with open("/content/sample_data/random_forest_model.pkl", "rb") as f:
#     model = pickle.load(f)
# 
# st.title("California Housing Price Prediction")
# 
# st.sidebar.header("Input Features")
# 
# longitude = st.sidebar.number_input("Longitude", float(train_df['longitude'].min()), float(train_df['longitude'].max()))
# latitude = st.sidebar.number_input("Latitude", float(train_df['latitude'].min()), float(train_df['latitude'].max()))
# housing_median_age = st.sidebar.number_input("Housing Median Age", float(train_df['housing_median_age'].min()), float(train_df['housing_median_age'].max()))
# total_rooms = st.sidebar.number_input("Total Rooms", float(train_df['total_rooms'].min()), float(train_df['total_rooms'].max()))
# total_bedrooms = st.sidebar.number_input("Total Bedrooms", float(train_df['total_bedrooms'].min()), float(train_df['total_bedrooms'].max()))
# population = st.sidebar.number_input("Population", float(train_df['population'].min()), float(train_df['population'].max()))
# households = st.sidebar.number_input("Households", float(train_df['households'].min()), float(train_df['households'].max()))
# median_income = st.sidebar.number_input("Median Income", float(train_df['median_income'].min()), float(train_df['median_income'].max()))
# 
# if st.button("Predict"):
#     features = np.array([[longitude, latitude, housing_median_age, total_rooms,
#                           total_bedrooms, population, households, median_income]])
#     prediction = model.predict(features)
#     st.success(f"Predicted Median House Value: ${prediction[0]:,.2f}")
#

!pkill streamlit

!streamlit run streamlit_app.py &>/content/logs.txt &

import streamlit as st
import pandas as pd
import numpy as np
import pickle

# Load training data (needed for min/max ranges)
train_data_path = "/content/sample_data/california_housing_train.csv"
train_df = pd.read_csv(train_data_path)

# Load model
with open("/content/sample_data/random_forest_model.pkl", "rb") as f:
    model = pickle.load(f)

st.title("California Housing Price Prediction")

# Sidebar inputs
st.sidebar.header("Input Features")

longitude = st.sidebar.number_input("Longitude", float(train_df['longitude'].min()), float(train_df['longitude'].max()))
latitude = st.sidebar.number_input("Latitude", float(train_df['latitude'].min()), float(train_df['latitude'].max()))
housing_median_age = st.sidebar.number_input("Housing Median Age", float(train_df['housing_median_age'].min()), float(train_df['housing_median_age'].max()))
total_rooms = st.sidebar.number_input("Total Rooms", float(train_df['total_rooms'].min()), float(train_df['total_rooms'].max()))
total_bedrooms = st.sidebar.number_input("Total Bedrooms", float(train_df['total_bedrooms'].min()), float(train_df['total_bedrooms'].max()))
population = st.sidebar.number_input("Population", float(train_df['population'].min()), float(train_df['population'].max()))
households = st.sidebar.number_input("Households", float(train_df['households'].min()), float(train_df['households'].max()))
median_income = st.sidebar.number_input("Median Income", float(train_df['median_income'].min()), float(train_df['median_income'].max()))

if st.button("Predict"):
    features = np.array([[longitude, latitude, housing_median_age, total_rooms,
                          total_bedrooms, population, households, median_income]])
    prediction = model.predict(features)
    st.success(f"Predicted Median House Value: ${prediction[0]:,.2f}")

# Save your Streamlit code to a file
app_code = """
import streamlit as st
import pandas as pd
import pickle

st.title("California Housing Predictor")

# Example code: load model if exists
with open("model.pkl", "rb") as f:
    model = pickle.load(f)

st.write("Streamlit app is ready")
"""

with open("streamlit_app.py", "w") as f:
    f.write(app_code)

import pickle

# My trained model is called 'model'
# Save it as 'model.pkl' in the same folder
with open("model.pkl", "wb") as f:
    pickle.dump(model, f)

!pip install pyngrok

!ngrok authtoken 35b93U5slx2vDv7m5iSyhft5tfg_3cUFuUEWxgD5JVWCEWtEm

!ngrok config add-authtoken 35b93U5slx2vDv7m5iSyhft5tfg_3cUFuUEWxgD5JVWCEWtEm

from pyngrok import ngrok
import os

# Start Streamlit
os.system("streamlit run /content/streamlit_app.py &")

# Open ngrok tunnel
public_url = ngrok.connect(8501)
print("Your app is live at:", public_url)