# -*- coding: utf-8 -*-
"""Hope_Nyambura_cs-eh03-25100-C.Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Fidl_fcaxcRsfky0sapULAJ4889LviU
"""

# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

# Load Wine dataset
wine = load_wine()
X = pd.DataFrame(wine.data, columns=wine.feature_names)
y = pd.Series(wine.target, name='target')

# Basic info
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)
print("\nClasses:", wine.target_names)
print("\nFirst 5 rows of data:")
display(X.head())

# Check for missing values
print("\nMissing values in dataset:")
print(X.isnull().sum())

# Summary statistics
display(X.describe())

# Pairplot for first few features (to visualize class separation)
sns.pairplot(pd.concat([X.iloc[:, :5], y], axis=1), hue='target', diag_kind='kde')
plt.show()

# Correlation heatmap
plt.figure(figsize=(12,8))
sns.heatmap(X.corr(), cmap='coolwarm')
plt.title("Feature Correlation Heatmap")
plt.show()

# Feature scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train/Test Split (70% training, 30% testing)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

print("Training set size:", X_train.shape)
print("Testing set size:", X_test.shape)

def plot_conf_matrix(y_true, y_pred, title):
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=wine.target_names, yticklabels=wine.target_names)
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.title(f'Confusion Matrix: {title}')
    plt.show()

# Results DataFrame
results = pd.DataFrame(columns=['Model', 'Accuracy'])

# 1. Logistic Regression
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)
results.loc[len(results)] = ['Logistic Regression', accuracy_score(y_test, y_pred_lr)]
print("Logistic Regression:\n", classification_report(y_test, y_pred_lr))
plot_conf_matrix(y_test, y_pred_lr, "Logistic Regression")

# 2. Decision Tree
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)
results.loc[len(results)] = ['Decision Tree', accuracy_score(y_test, y_pred_dt)]
print("Decision Tree:\n", classification_report(y_test, y_pred_dt))
plot_conf_matrix(y_test, y_pred_dt, "Decision Tree")

# 3. Random Forest
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)
results.loc[len(results)] = ['Random Forest', accuracy_score(y_test, y_pred_rf)]
print("Random Forest:\n", classification_report(y_test, y_pred_rf))
plot_conf_matrix(y_test, y_pred_rf, "Random Forest")

# 4. K-Nearest Neighbors
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred_knn = knn.predict(X_test)
results.loc[len(results)] = ['KNN', accuracy_score(y_test, y_pred_knn)]
print("K-Nearest Neighbors:\n", classification_report(y_test, y_pred_knn))
plot_conf_matrix(y_test, y_pred_knn, "KNN")

# 5. Naive Bayes
nb = GaussianNB()
nb.fit(X_train, y_train)
y_pred_nb = nb.predict(X_test)
results.loc[len(results)] = ['Naive Bayes', accuracy_score(y_test, y_pred_nb)]
print("Naive Bayes:\n", classification_report(y_test, y_pred_nb))
plot_conf_matrix(y_test, y_pred_nb, "Naive Bayes")

# 6. Support Vector Machine
svm = SVC(kernel='linear')
svm.fit(X_train, y_train)
y_pred_svm = svm.predict(X_test)
results.loc[len(results)] = ['SVM', accuracy_score(y_test, y_pred_svm)]
print("Support Vector Machine:\n", classification_report(y_test, y_pred_svm))
plot_conf_matrix(y_test, y_pred_svm, "Support Vector Machine")

# Compare model accuracies
results.sort_values(by='Accuracy', ascending=False, inplace=True)
plt.figure(figsize=(8,5))
sns.barplot(x='Accuracy', y='Model', data=results, palette='viridis')
plt.title('Model Performance Comparison')
plt.show()

display(results)

from sklearn.model_selection import cross_val_score

# Evaluate models using 5-fold cross-validation
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42),
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "Naive Bayes": GaussianNB(),
    "SVM": SVC(kernel='linear')
}

cv_results = []

for name, model in models.items():
    scores = cross_val_score(model, X_scaled, y, cv=5)
    mean_acc = scores.mean()
    cv_results.append({'Model': name, 'CV Mean Accuracy': mean_acc})

cv_df = pd.DataFrame(cv_results).sort_values(by='CV Mean Accuracy', ascending=False)

# Display results
plt.figure(figsize=(8,5))
sns.barplot(x='CV Mean Accuracy', y='Model', data=cv_df, palette='mako')
plt.title('5-Fold Cross-Validation Mean Accuracy')
plt.show()

display(cv_df)