# -*- coding: utf-8 -*-
"""Hope_Nyambura_cs-eh03-25100

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/scratchpad/hope-nyambura-cs-eh03-25100.cb345dcb-73f3-4e44-a7f4-ca579c69dbc4.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20251126/auto/storage/goog4_request%26X-Goog-Date%3D20251126T180331Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D993e0e9ac7d55c626a4e4f369775bf9f3f60851ac5da33e98d06855ea29e23a317f17c1a08856789a1121070a49092cc59386b688c0696795f10e48873a47a500f5e160785620f9bc0039328abbfaa95ec17e77aa881c5e3071e2b2b496307c416c9de838317024efcf3b0243add0116556f52f2e8ba23cf7769a1786fbd70a7303c3f88ce0d7495496a9d10be00c7fced1dcd167d71a6efb456be9868a6e9d3a32ce7e51dffcb67c46b39cf45686cc90fe53617246d12d4f68cfeaac5f5fb4567e7d2df7cd8f3364bef19bb0ed74688d262d05362c0063748f8d93f077e911a0d4aa5530aad46a103dbfa4c0ce4c05c4d9f73feb5e4d487868695a17f19e0c6
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
shivamb_netflix_shows_path = kagglehub.dataset_download('shivamb/netflix-shows')

print('Data source import complete.')

# Title: Data Wrangling Project
# Name: Hope Njoki Nyambura
# Date: 24/09/2025

import pandas as pd
import numpy as np
import datetime as dt

# Load the dataset
df = pd.read_csv('/kaggle/input/netflix-shows/netflix_titles.csv')

# Overview
df.info()
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print("Missing values:\n", df.isnull().sum())
print("Duplicates:", df.duplicated().sum())

# Convert date_added to datetime
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

# Split duration into value and unit
df[['duration_value', 'duration_unit']] = df['duration'].str.extract(r'(\d+)\s*(\w+)')
df['duration_value'] = pd.to_numeric(df['duration_value'])

# Remove duplicates
df = df.drop_duplicates()

# Drop description (ignore if already dropped)
df = df.drop(columns=['description'], errors='ignore')

# Fill missing values
df['director'] = df['director'].fillna('Not Given')
df['cast'] = df['cast'].fillna('Not Given')
df['country'] = df['country'].fillna('Not Given')

# Drop rows with missing critical fields
df = df.dropna(subset=['date_added', 'rating', 'duration'])

# Check results
print("Missing values after cleaning:\n", df.isnull().sum())

# Find records where added date < release year
invalid = df[df['date_added'].dt.year < df['release_year']]
print("Inconsistent rows:", invalid.shape[0])

# Drop inconsistencies if necessary
df = df[~(df['date_added'].dt.year < df['release_year'])]

# Reset index
df = df.reset_index(drop=True)

# Save cleaned dataset
df.to_csv('/kaggle/working/cleaned_netflix.csv', index=False)

print(df.dtypes)  # confirm types
print("Earliest release year:", df['release_year'].min())
print("Latest release year:", df['release_year'].max())
print(df.sample(5))  # visual spot-check