# -*- coding: utf-8 -*-
"""Hope-Nyambura_cs-eh03-25100-DL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1skrT0zhLRXXjA_hmASWDRR8F9iSKU3Cv

# Deep Learning – MNIST Digit Classification
**Student Name:** Hope Njoki Nyambura  
**Student ID:** cs-eh03-25100
"""

# Import Libraries
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Flatten, Dense, Dropout
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import confusion_matrix, classification_report

# Load MNIST Data
(X_train, y_train), (X_test, y_test) = mnist.load_data()

print("Training set:", X_train.shape, y_train.shape)
print("Testing set:", X_test.shape, y_test.shape)

# Visualize 9 Random Images
indices = np.random.choice(len(X_train), 9, replace=False)

plt.figure(figsize=(8,8))
for i, idx in enumerate(indices):
    plt.subplot(3,3,i+1)
    plt.imshow(X_train[idx], cmap='gray')
    plt.title(f"Label: {y_train[idx]}")
    plt.axis('off')
plt.tight_layout()
plt.show()

# Preprocessing: Normalize + One-hot Encoding
X_train = X_train / 255.0
X_test = X_test / 255.0

y_train_cat = to_categorical(y_train, 10)
y_test_cat = to_categorical(y_test, 10)

print("X_train:", X_train.shape)
print("y_train_cat:", y_train_cat.shape)

# Build the ANN Model
model = Sequential([
    Flatten(input_shape=(28,28)),
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(10, activation='softmax')
])

model.summary()

# Compile Model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Train Model
history = model.fit(
    X_train, y_train_cat,
    epochs=10,
    batch_size=128,
    validation_split=0.1
)

# Evaluate Model
loss, accuracy = model.evaluate(X_test, y_test_cat)
print("Test Accuracy:", accuracy)

# Plot Training History (Accuracy)
plt.plot(history.history['accuracy'], label='Train')
plt.plot(history.history['val_accuracy'], label='Validation')
plt.title("Accuracy per Epoch")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.show()

# Predictions + Confusion Matrix
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)

cm = confusion_matrix(y_test, y_pred_classes)
plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.show()

# Classification Report
print(classification_report(y_test, y_pred_classes))

# Save Model
model.save("mnist_ann_model.h5")

# Reload Model
reloaded = load_model("mnist_ann_model.h5")
reloaded.evaluate(X_test, y_test_cat)