# -*- coding: utf-8 -*-
"""Hope_Nyambura_cs-eh03-25100-RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ThxzMG2kw3nA27oa16u21g4BgBe9Q3j
"""

# Assignment 12: Generative AI and RAG
# Objective: Build a RAG pipeline to answer questions using context from a PDF document

# Install required packages
!pip install --upgrade langchain langchain-community langchain-text-splitters sentence-transformers transformers faiss-cpu pypdf --quiet

# Import PDF loader
from langchain_community.document_loaders import PyPDFLoader

# Import text splitter
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Import embeddings from HuggingFace (community module)
from langchain_community.embeddings.huggingface import HuggingFaceEmbeddings

# Import FAISS vector store
from langchain_community.vectorstores.faiss import FAISS

# Import transformers pipeline
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline

# Print versions for referencing in the report
import langchain, transformers, sentence_transformers, faiss, pypdf
print("LangChain version:", langchain.__version__)
print("Transformers version:", transformers.__version__)
print("Sentence-Transformers version:", sentence_transformers.__version__)
print("FAISS version:", faiss.__version__)
print("PyPDF version:", pypdf.__version__)

# Upload the PDF file to Colab
from google.colab import files

uploaded = files.upload()  # This will open a file picker
pdf_filename = list(uploaded.keys())[0]  # Get the uploaded file name

# Load the PDF
loader = PyPDFLoader(pdf_filename)
docs = loader.load()

# Split into chunks
splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)
chunks = splitter.split_documents(docs)

# Preview
print("Number of chunks:", len(chunks))
print("First chunk preview:\n", chunks[0].page_content[:200], "...")

# Create embeddings for each chunk and build the FAISS vector store
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
vectorstore = FAISS.from_documents(chunks, embeddings)
retriever = vectorstore.as_retriever()

print("Vector store created. Retriever is ready.")

# Query function using FAISS directly (no LangChain chains)
def query_rag(question, top_k=3):
    # Get top-k similar documents
    results = vectorstore.similarity_search(question, k=top_k)

    # Combine content from retrieved chunks
    context = "\n".join([doc.page_content for doc in results])

    # Prepare the prompt
    prompt = f"Answer the question using only the context:\n\nContext:\n{context}\n\nQuestion: {question}\n\nAnswer:"

    # Generate answer with Flan-T5 pipeline
    response = flan_pipeline(
        prompt,
        max_new_tokens=200,
        temperature=0.9,
        top_k=50,
        top_p=0.9,
        do_sample=True
    )

    return response[0]['generated_text']

# Test the function
print(query_rag("Summarize the key points of this document in a paragraph of 200 words."))

# Additional queries for the RAG pipeline

# Example 1: Summarize the document
summary = query_rag("Provide a summary of the entire document in 200 words.")
print("Summary:\n", summary, "\n")

# Example 2: Ask a specific question about the document
question1 = query_rag("What are the main steps in the RAG pipeline described in this document?")
print("Answer 1:\n", question1, "\n")

# Example 3: Another question
question2 = query_rag("Explain how embeddings are created and used for retrieval in this assignment.")
print("Answer 2:\n", question2, "\n")

# Save RAG outputs to a file for the report

# Define questions to ask
questions = [
    "Summarize the entire document in 200 words.",
    "What are the main steps in the RAG pipeline described in this document?",
    "Explain how embeddings are created and used for retrieval in this assignment."
]

# Open a text file to save results
with open("rag_outputs.txt", "w") as f:
    for q in questions:
        answer = query_rag(q)
        f.write(f"Question: {q}\n")
        f.write(f"Answer: {answer}\n\n")

print("All answers saved to rag_outputs.txt")