# -*- coding: utf-8 -*-
"""Hope-Nyambura_cs-eh03-25100-MLOPs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zmkXJzFpFnYfJL0itleAVxQheZ_bcZAa
"""

# Import libraries
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
import pickle
from pathlib import Path
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score, mean_squared_error

# Load dataset
X, y = fetch_california_housing(return_X_y=True, as_frame=True)
print("X shape:", X.shape)
print("y shape:", y.shape)
display(X.head())
display(y.head())

# Train-test split (80/20)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Preprocessing (imputation and scaling for numeric features)
numeric_features = list(X.columns)

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features)
    ]
)

# Build pipeline (preprocessor + KNN)
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('knn', KNeighborsRegressor())
])
pipeline

# Define hyperparameter grid
param_grid = {
    'knn__n_neighbors': [3, 5, 7, 9],
    'knn__weights': ['uniform', 'distance'],
    'knn__p': [1, 2]
}

# GridSearchCV setup
grid_search = GridSearchCV(
    estimator=pipeline,
    param_grid=param_grid,
    cv=5,
    scoring='r2',
    verbose=2,
    n_jobs=-1,
    return_train_score=True
)

# Fit GridSearchCV
grid_search.fit(X_train, y_train)

# Evaluate model
best_model = grid_search.best_estimator_
best_params = grid_search.best_params_
best_cv_score = grid_search.best_score_

y_pred = best_model.predict(X_test)

r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = mse ** 0.5   # instead of squared=False

print("Best Parameters:", best_params)
print("Best CV R2 Score:", best_cv_score)
print("Test R2 Score:", r2)
print("Test MSE:", mse)
print("Test RMSE:", rmse)

# View CV results
cv_results = pd.DataFrame(grid_search.cv_results_)
cols = ['params','mean_test_score','std_test_score','mean_train_score','rank_test_score']
display(cv_results[cols].sort_values('rank_test_score').head(10))

# Save trained pipeline as .pkl
output_dir = Path('/content/models')
output_dir.mkdir(parents=True, exist_ok=True)

model_path = output_dir / 'california_knn_pipeline.pkl'
with open(model_path, 'wb') as f:
    pickle.dump(best_model, f)

print("Model saved at:", model_path)

# Example prediction using saved model
with open(model_path, 'rb') as f:
    loaded_model = pickle.load(f)

sample = X_test.iloc[:3]
print("Sample prediction:", loaded_model.predict(sample))

from google.colab import files

# Download the saved model to your local computer
files.download('/content/models/california_knn_pipeline.pkl')