# -*- coding: utf-8 -*-
"""Hope_Nyambura_cs-eh03-25100-NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Xv_gdlRgFPXRfAHyPT4bECP5DlewzWf
"""

# Student Name: Hope Njoki Nyambura
# Student ID: cs-eh03-25100
# NLP Assignment - BERT Sentence Similarity

# install transformers
!pip install transformers -q

# import libraries
from transformers import BertTokenizer, BertModel
import torch
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# load tokenizer and model (pytorch)
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
bert_model = BertModel.from_pretrained('bert-base-uncased')

# sentence pairs and labels
sentence_pairs = [
    ("How do I learn Python?", "What is the best way to study Python?"),
    ("What is AI?", "How to cook pasta?"),
    ("How do I bake a chocolate cake?", "Give me a chocolate cake recipe."),
    ("How can I improve my coding skills?", "Tips for becoming better at programming."),
    ("Where can I buy cheap laptops?", "Best sites to find affordable computers."),

    ("I love playing football on weekends.", "Football is my favorite weekend activity."),
    ("The sun is very hot today.", "It is extremely cold outside right now."),
    ("She bought a new smartphone yesterday.", "He purchased a brand-new mobile phone."),
    ("I need to book a flight to Nairobi.", "Where can I find cheap air tickets to Nairobi?"),
    ("Cats are very playful animals.", "Cars require fuel to operate."),
]

labels = [1,0,1,1,1, 1,0,1,1,0]

# get CLS embedding
def get_sentence_embedding(sentence):
    inputs = tokenizer(sentence, return_tensors='pt', padding=True, truncation=True)
    outputs = bert_model(**inputs)
    cls_emb = outputs.last_hidden_state[:, 0, :].detach().numpy()
    return cls_emb

# compute similarities
predictions = []

for s1, s2 in sentence_pairs:
    emb1 = get_sentence_embedding(s1)
    emb2 = get_sentence_embedding(s2)

    sim = cosine_similarity(emb1, emb2)[0][0]
    pred = 1 if sim > 0.7 else 0
    predictions.append(pred)

    print("Sentence 1:", s1)
    print("Sentence 2:", s2)
    print("Similarity:", sim)
    print("Prediction:", pred)
    print()

# calculate accuracy
correct = 0

for i in range(len(labels)):
    if predictions[i] == labels[i]:
        correct += 1

accuracy = correct / len(labels)
print("Accuracy:", accuracy)