# -*- coding: utf-8 -*-
"""Hope_Nyambura_cs-eh03-25100-Regression-Models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zy9VVazlNpC6Y2iqy8AlK5pMNIByoaNN
"""

# Commented out IPython magic to ensure Python compatibility.
# Assignment 7: Regression Models
# Cyber Shujaa Program - Data and Artificial Intelligence
# Student Name: Hope Njoki Nyambura
# Student ID: cs-eh03-25100

# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
# %matplotlib inline

# upload file from local computer
from google.colab import files
uploaded = files.upload()

# load dataset
df = pd.read_csv('homeprices.csv')

# display first few rows
df.head()

# visualize the data
plt.scatter(df['area'], df['price'], color='red', marker='+')
plt.xlabel('Area (sq ft)')
plt.ylabel('Price')
plt.title('Area vs Price')
plt.show()

# build and train linear regression model
model = LinearRegression()
model.fit(df[['area']], df['price'])

# visualize regression line
plt.scatter(df['area'], df['price'], color='blue', label='Actual data')
plt.plot(df['area'], model.predict(df[['area']]), color='red', label='Regression line')
plt.xlabel('Area (sq ft)')
plt.ylabel('Price')
plt.title('Linear Regression: Area vs Price')
plt.legend()
plt.show()

# upload areas.csv file
from google.colab import files
uploaded = files.upload()

# load new areas dataset
area_df = pd.read_csv("areas.csv")

# predict prices
predicted_prices = model.predict(area_df)

# add predicted prices to dataframe
area_df['price'] = predicted_prices

# save predictions to csv
area_df.to_csv("prediction.csv", index=False)

# show predictions
area_df.head()

# upload multi-variable dataset
from google.colab import files
uploaded = files.upload()

# load multi-variable dataset
dfm = pd.read_csv('homeprices-m.csv')

# fill missing values in 'bedrooms' with median
dfm.bedrooms = dfm.bedrooms.fillna(dfm.bedrooms.median())

# create and train the model
mreg = LinearRegression()
mreg.fit(dfm[['area', 'bedrooms', 'age']], dfm['price'])

# show coefficients and intercept
mreg.coef_, mreg.intercept_

# predict price for a 3000 sq ft house, 3 bedrooms, 40 years old
mreg.predict([[3000, 3, 40]])