# -*- coding: utf-8 -*-
"""Hope_Nyambura_cs-eh03-25100_EDA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/scratchpad/hope-nyambura-cs-eh03-25100-eda.c9be723d-6c4e-49e2-8bcb-1f3335c7b3ab.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20251126/auto/storage/goog4_request%26X-Goog-Date%3D20251126T180602Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D5ab314647d1f57e6935cc6135383bc379498cd842c7d033c5ff13f2e1e77aa45c43384a469ada8dec7752aa7595089d1651f3bedd9dc3cdef89e74f2d157f1f31d3d71ff5386df814e462e9454abccff927d9503466d575e9f316ee69a3efe188a6fe2f582f9dce70f628669feb30a3483f2895c1331c3df9aeb8f175a85abe8e61a1548236f0f424fa0e7fcdb12d0957bc7b737ad9ff294d1e8df8618fce5e83197d59077f0f9fdd0924a471e41e6c8f8703c57b7879fe9f65caa6d71a6028495fee78a7282d5b1e3a849db2945e0f36e5c4b03d0043d58d746c231ebd269132fe1e66aabcfa31f11df6cfb25bcde0da5e636fcae4ab1dc973b2ef8a618a7f4
"""

# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

titanic_path = kagglehub.competition_download('titanic')

print('Data source import complete.')

# Commented out IPython magic to ensure Python compatibility.
# Step 1: Import Libraries

import pandas as pd      # For data handling
import numpy as np       # For numerical operations
import matplotlib.pyplot as plt  # For plotting
import seaborn as sns    # For advanced visualization

# Make plots look nicer
# %matplotlib inline
sns.set(style="whitegrid")

# Step 2: Load Dataset

# Load the Titanic dataset (make sure 'train.csv' is in your Kaggle notebook directory)
df = pd.read_csv("/kaggle/input/titanic/train.csv")

# Quick check: show first 5 rows
df.head()

# Step 3: Initial Data Exploration

# Shape of the dataset (rows, columns)
print("Shape of dataset:", df.shape)

# Info about columns: names, data types, non-null counts
print("\n--- Dataset Info ---")
print(df.info())

# Summary statistics for numerical features
print("\n--- Summary Statistics ---")
print(df.describe())

# Check column names
print("\n--- Columns ---")
print(df.columns)

# Count unique values per column
print("\n--- Unique values per column ---")
print(df.nunique())

# Check duplicates
print("\n--- Number of duplicate rows ---")
print(df.duplicated().sum())

# Quick check for missing values
print("\n--- Missing values per column ---")
print(df.isnull().sum())

# Step 4: Handling Missing Values and Outliers

# Check missing values again
print("Missing values before handling:\n", df.isnull().sum())

# 1. Handle 'Age' missing values → fill with median (reasonable since age is continuous)
df['Age'].fillna(df['Age'].median(), inplace=True)

# 2. Handle 'Embarked' missing values → fill with the most common value (mode)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

# 3. Handle 'Cabin' missing values → too many missing, so drop the column
df.drop(columns=['Cabin'], inplace=True)

# Confirm missing values handled
print("\nMissing values after handling:\n", df.isnull().sum())

# ---- Outliers ----
# Visualize outliers in 'Age' and 'Fare' using boxplots
plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
sns.boxplot(x=df['Age'])
plt.title("Age Outliers")

plt.subplot(1,2,2)
sns.boxplot(x=df['Fare'])
plt.title("Fare Outliers")

plt.show()

# Step 5: Univariate Analysis

# 1. Age distribution
plt.figure(figsize=(8,5))
sns.histplot(df['Age'], bins=30, kde=True)
plt.title("Age Distribution of Passengers")
plt.xlabel("Age")
plt.ylabel("Count")
plt.show()

# 2. Sex distribution
plt.figure(figsize=(6,4))
sns.countplot(x='Sex', data=df)
plt.title("Passenger Count by Sex")
plt.xlabel("Sex")
plt.ylabel("Count")
plt.show()

# 3. Passenger Class distribution
plt.figure(figsize=(6,4))
sns.countplot(x='Pclass', data=df)
plt.title("Passenger Count by Class")
plt.xlabel("Passenger Class")
plt.ylabel("Count")
plt.show()

# 4. Fare distribution
plt.figure(figsize=(8,5))
sns.histplot(df['Fare'], bins=40, kde=True)
plt.title("Fare Distribution of Passengers")
plt.xlabel("Fare")
plt.ylabel("Count")
plt.show()

# 5. Embarked distribution
plt.figure(figsize=(6,4))
sns.countplot(x='Embarked', data=df)
plt.title("Passenger Count by Embarkation Point")
plt.xlabel("Port of Embarkation (C = Cherbourg, Q = Queenstown, S = Southampton)")
plt.ylabel("Count")
plt.show()

# Step 6: Bivariate Analysis

# 1. Survival by Sex
plt.figure(figsize=(6,4))
sns.countplot(x='Sex', hue='Survived', data=df)
plt.title("Survival by Sex")
plt.xlabel("Sex")
plt.ylabel("Count")
plt.show()

# 2. Survival by Passenger Class
plt.figure(figsize=(6,4))
sns.countplot(x='Pclass', hue='Survived', data=df)
plt.title("Survival by Passenger Class")
plt.xlabel("Pclass")
plt.ylabel("Count")
plt.show()

# 3. Survival by Age (distribution with KDE)
plt.figure(figsize=(8,5))
sns.kdeplot(data=df[df['Survived']==1]['Age'], shade=True, label="Survived")
sns.kdeplot(data=df[df['Survived']==0]['Age'], shade=True, label="Did Not Survive")
plt.title("Survival by Age")
plt.xlabel("Age")
plt.ylabel("Density")
plt.legend()
plt.show()

# 4. Survival by Fare
plt.figure(figsize=(8,5))
sns.boxplot(x='Survived', y='Fare', data=df)
plt.title("Survival by Fare")
plt.xlabel("Survived (0 = No, 1 = Yes)")
plt.ylabel("Fare")
plt.show()

# 5. Survival by Embarked
plt.figure(figsize=(6,4))
sns.countplot(x='Embarked', hue='Survived', data=df)
plt.title("Survival by Embarked Port")
plt.xlabel("Embarked")
plt.ylabel("Count")
plt.show()

# Step 7: Multivariate Analysis

# 1. Survival by Pclass and Sex
plt.figure(figsize=(8,5))
sns.catplot(x='Pclass', hue='Sex', col='Survived', kind='count', data=df, height=5, aspect=1)
plt.subplots_adjust(top=0.8)
plt.suptitle("Survival by Passenger Class and Sex")
plt.show()

# 2. Age vs Fare vs Survival
plt.figure(figsize=(10,6))
sns.scatterplot(x='Age', y='Fare', hue='Survived', style='Pclass', data=df, palette='Set2')
plt.title("Age, Fare, and Survival (with Pclass)")
plt.xlabel("Age")
plt.ylabel("Fare")
plt.legend()
plt.show()

# 3. Survival by Embarked and Pclass
plt.figure(figsize=(8,5))
sns.catplot(x='Embarked', hue='Survived', col='Pclass', kind='count', data=df, height=5, aspect=1)
plt.subplots_adjust(top=0.8)
plt.suptitle("Survival by Embarked Port and Passenger Class")
plt.show()

# Step 8: Target Variable Analysis

# 1. Distribution of Survived (0 = No, 1 = Yes)
plt.figure(figsize=(6,4))
sns.countplot(x='Survived', data=df)
plt.title("Distribution of Survival")
plt.xlabel("Survived (0 = No, 1 = Yes)")
plt.ylabel("Count")
plt.show()

# Check balance
survival_counts = df['Survived'].value_counts(normalize=True) * 100
print("Survival distribution (%):\n", survival_counts)

# 2. Survival by Sex
plt.figure(figsize=(6,4))
sns.barplot(x='Sex', y='Survived', data=df)
plt.title("Survival Rate by Sex")
plt.ylabel("Survival Rate")
plt.show()

# 3. Survival by Passenger Class
plt.figure(figsize=(6,4))
sns.barplot(x='Pclass', y='Survived', data=df)
plt.title("Survival Rate by Class")
plt.ylabel("Survival Rate")
plt.show()

# 4. Survival by Embarked
plt.figure(figsize=(6,4))
sns.barplot(x='Embarked', y='Survived', data=df)
plt.title("Survival Rate by Embarked Port")
plt.ylabel("Survival Rate")
plt.show()