# -*- coding: utf-8 -*-
"""Hope_Nyambura_cs-eh03-25100.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fXNAbQ2FdOBNoYhJ2bmgZO1ZllqPy0m9
"""

'''
Title : Web Scraping Project
Name : Hope Njoki Nyambura
Student Id : cs-eh03-25100
Date : 18/09/2025
Description : Buiding a web scraper using Requests, BeautifulSoup and Pandas
'''

# Import Libraries
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Set URL of website in a variable
url = 'https://www.scrapethissite.com/pages/forms/'
page = requests.get(url)

# Use BeautifulSoup to extract the HTML content
soup = BeautifulSoup(page.text, 'html.parser')
print(soup)

# Extract the table with the Hockey Scores
hockey_table = soup.find('table', class_='table')
print(hockey_table)

# Extract the column headings
table_titles = hockey_table.find_all('th')
hockey_table_title = [title.text.strip() for title in table_titles]
print(hockey_table_title)

# Save the column headings into a Pandas DataFrame
df = pd.DataFrame(columns=hockey_table_title)
df

# Extract the data row by row
table_data = hockey_table.find_all('tr')

for row in table_data[1:]:   # skip the header row
    raw_data = row.find_all('td')
    each_raw_data = [data.text.strip() for data in raw_data]
    print(each_raw_data)   # check each row as it is extracted

    # Add each row to the DataFrame
    length = len(df)
    df.loc[length] = each_raw_data

# Show the first few rows of the DataFrame
df.head()

# Save the DataFrame to a CSV file
df.to_csv('Hockey.csv', index=False)

print("CSV file saved as Hockey.csv")

# Confirm file exists
import os

print("File exists?", os.path.exists("Hockey.csv"))

# Download file directly to my computer
from google.colab import files

files.download("Hockey.csv")